// Code generated by alef — DO NOT EDIT.
// alef:hash:ad1468690f61db50741156a4c3c54b2824b25bce6004accbeda6484a6d43fc3f
package xberg

// RequireNativeSetup_1_3_7 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_3_7 = "1.3.7"
