/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require("fs");
let nativeBinding = null;
// Which artifact actually loaded. The WASI fallback chain overwrites it with
// the flavor it resolved; the late native retry below leaves it alone because
// it only runs while no WASI candidate has been loaded.
let __napiLoadedBindingTarget = "native";
const loadErrors = [];

const isMusl = () => {
  let musl = false;
  if (process.platform === "linux") {
    musl = isMuslFromFilesystem();
    if (musl === null) {
      musl = isMuslFromReport();
    }
    if (musl === null) {
      musl = isMuslFromChildProcess();
    }
  }
  return musl;
};

const isFileMusl = (f) => f.includes("libc.musl-") || f.includes("ld-musl-");

const isMuslFromFilesystem = () => {
  try {
    return readFileSync("/usr/bin/ldd", "utf-8").includes("musl");
  } catch {
    return null;
  }
};

const isMuslFromReport = () => {
  let report = null;
  if (process.report && typeof process.report.getReport === "function") {
    process.report.excludeNetwork = true;
    report = process.report.getReport();
  }
  if (!report) {
    return null;
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false;
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true;
    }
  }
  return false;
};

const isMuslFromChildProcess = () => {
  try {
    return require("child_process").execSync("ldd --version", { encoding: "utf8" }).includes("musl");
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false;
  }
};

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      const overrideBinding = require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
      // The override may be a generated WASI loader, which already reports its
      // own flavor. Adopt it: `module.exports` aliases this object, so claiming
      // 'native' would both misreport the artifact and overwrite the loader's
      // marker through the alias.
      __napiLoadedBindingTarget =
        overrideBinding && typeof overrideBinding.__napiBindingTarget === "string"
          ? overrideBinding.__napiBindingTarget
          : "native";
      return overrideBinding;
    } catch (err) {
      loadErrors.push(err);
    }
  } else if (process.platform === "android") {
    if (process.arch === "arm64") {
      try {
        return require("./xberg-node.android-arm64.node");
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require("@xberg-io/xberg-android-arm64");
        const bindingPackageVersion = require("@xberg-io/xberg-android-arm64/package.json").version;
        if (
          bindingPackageVersion !== "1.3.7" &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === "arm") {
      try {
        return require("./xberg-node.android-arm-eabi.node");
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require("@xberg-io/xberg-android-arm-eabi");
        const bindingPackageVersion = require("@xberg-io/xberg-android-arm-eabi/package.json").version;
        if (
          bindingPackageVersion !== "1.3.7" &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`));
    }
  } else if (process.platform === "win32") {
    if (process.arch === "x64") {
      if (
        (process.config && process.config.variables && process.config.variables.shlib_suffix === "dll.a") ||
        (process.config && process.config.variables && process.config.variables.node_target_type === "shared_library")
      ) {
        try {
          return require("./xberg-node.win32-x64-gnu.node");
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require("@xberg-io/xberg-win32-x64-gnu");
          const bindingPackageVersion = require("@xberg-io/xberg-win32-x64-gnu/package.json").version;
          if (
            bindingPackageVersion !== "1.3.7" &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require("./xberg-node.win32-x64-msvc.node");
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require("@xberg-io/xberg-win32-x64-msvc");
          const bindingPackageVersion = require("@xberg-io/xberg-win32-x64-msvc/package.json").version;
          if (
            bindingPackageVersion !== "1.3.7" &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === "ia32") {
      try {
        return require("./xberg-node.win32-ia32-msvc.node");
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require("@xberg-io/xberg-win32-ia32-msvc");
        const bindingPackageVersion = require("@xberg-io/xberg-win32-ia32-msvc/package.json").version;
        if (
          bindingPackageVersion !== "1.3.7" &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === "arm64") {
      try {
        return require("./xberg-node.win32-arm64-msvc.node");
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require("@xberg-io/xberg-win32-arm64-msvc");
        const bindingPackageVersion = require("@xberg-io/xberg-win32-arm64-msvc/package.json").version;
        if (
          bindingPackageVersion !== "1.3.7" &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`));
    }
  } else if (process.platform === "darwin") {
    try {
      return require("./xberg-node.darwin-universal.node");
    } catch (e) {
      loadErrors.push(e);
    }
    try {
      const binding = require("@xberg-io/xberg-darwin-universal");
      const bindingPackageVersion = require("@xberg-io/xberg-darwin-universal/package.json").version;
      if (
        bindingPackageVersion !== "1.3.7" &&
        process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
        process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
      ) {
        throw new Error(
          `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
        );
      }
      return binding;
    } catch (e) {
      loadErrors.push(e);
    }
    if (process.arch === "x64") {
      try {
        return require("./xberg-node.darwin-x64.node");
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require("@xberg-io/xberg-darwin-x64");
        const bindingPackageVersion = require("@xberg-io/xberg-darwin-x64/package.json").version;
        if (
          bindingPackageVersion !== "1.3.7" &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === "arm64") {
      try {
        return require("./xberg-node.darwin-arm64.node");
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require("@xberg-io/xberg-darwin-arm64");
        const bindingPackageVersion = require("@xberg-io/xberg-darwin-arm64/package.json").version;
        if (
          bindingPackageVersion !== "1.3.7" &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`));
    }
  } else if (process.platform === "freebsd") {
    if (process.arch === "x64") {
      try {
        return require("./xberg-node.freebsd-x64.node");
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require("@xberg-io/xberg-freebsd-x64");
        const bindingPackageVersion = require("@xberg-io/xberg-freebsd-x64/package.json").version;
        if (
          bindingPackageVersion !== "1.3.7" &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === "arm64") {
      try {
        return require("./xberg-node.freebsd-arm64.node");
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require("@xberg-io/xberg-freebsd-arm64");
        const bindingPackageVersion = require("@xberg-io/xberg-freebsd-arm64/package.json").version;
        if (
          bindingPackageVersion !== "1.3.7" &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`));
    }
  } else if (process.platform === "linux") {
    if (process.arch === "x64") {
      if (isMusl()) {
        try {
          return require("./xberg-node.linux-x64-musl.node");
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require("@xberg-io/xberg-linux-x64-musl");
          const bindingPackageVersion = require("@xberg-io/xberg-linux-x64-musl/package.json").version;
          if (
            bindingPackageVersion !== "1.3.7" &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require("./xberg-node.linux-x64-gnu.node");
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require("@xberg-io/xberg-linux-x64-gnu");
          const bindingPackageVersion = require("@xberg-io/xberg-linux-x64-gnu/package.json").version;
          if (
            bindingPackageVersion !== "1.3.7" &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === "arm64") {
      if (isMusl()) {
        try {
          return require("./xberg-node.linux-arm64-musl.node");
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require("@xberg-io/xberg-linux-arm64-musl");
          const bindingPackageVersion = require("@xberg-io/xberg-linux-arm64-musl/package.json").version;
          if (
            bindingPackageVersion !== "1.3.7" &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require("./xberg-node.linux-arm64-gnu.node");
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require("@xberg-io/xberg-linux-arm64-gnu");
          const bindingPackageVersion = require("@xberg-io/xberg-linux-arm64-gnu/package.json").version;
          if (
            bindingPackageVersion !== "1.3.7" &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === "arm") {
      if (isMusl()) {
        try {
          return require("./xberg-node.linux-arm-musleabihf.node");
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require("@xberg-io/xberg-linux-arm-musleabihf");
          const bindingPackageVersion = require("@xberg-io/xberg-linux-arm-musleabihf/package.json").version;
          if (
            bindingPackageVersion !== "1.3.7" &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require("./xberg-node.linux-arm-gnueabihf.node");
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require("@xberg-io/xberg-linux-arm-gnueabihf");
          const bindingPackageVersion = require("@xberg-io/xberg-linux-arm-gnueabihf/package.json").version;
          if (
            bindingPackageVersion !== "1.3.7" &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === "loong64") {
      if (isMusl()) {
        try {
          return require("./xberg-node.linux-loong64-musl.node");
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require("@xberg-io/xberg-linux-loong64-musl");
          const bindingPackageVersion = require("@xberg-io/xberg-linux-loong64-musl/package.json").version;
          if (
            bindingPackageVersion !== "1.3.7" &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require("./xberg-node.linux-loong64-gnu.node");
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require("@xberg-io/xberg-linux-loong64-gnu");
          const bindingPackageVersion = require("@xberg-io/xberg-linux-loong64-gnu/package.json").version;
          if (
            bindingPackageVersion !== "1.3.7" &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === "riscv64") {
      if (isMusl()) {
        try {
          return require("./xberg-node.linux-riscv64-musl.node");
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require("@xberg-io/xberg-linux-riscv64-musl");
          const bindingPackageVersion = require("@xberg-io/xberg-linux-riscv64-musl/package.json").version;
          if (
            bindingPackageVersion !== "1.3.7" &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require("./xberg-node.linux-riscv64-gnu.node");
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require("@xberg-io/xberg-linux-riscv64-gnu");
          const bindingPackageVersion = require("@xberg-io/xberg-linux-riscv64-gnu/package.json").version;
          if (
            bindingPackageVersion !== "1.3.7" &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === "ppc64") {
      try {
        return require("./xberg-node.linux-ppc64-gnu.node");
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require("@xberg-io/xberg-linux-ppc64-gnu");
        const bindingPackageVersion = require("@xberg-io/xberg-linux-ppc64-gnu/package.json").version;
        if (
          bindingPackageVersion !== "1.3.7" &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === "s390x") {
      try {
        return require("./xberg-node.linux-s390x-gnu.node");
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require("@xberg-io/xberg-linux-s390x-gnu");
        const bindingPackageVersion = require("@xberg-io/xberg-linux-s390x-gnu/package.json").version;
        if (
          bindingPackageVersion !== "1.3.7" &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`));
    }
  } else if (process.platform === "openharmony") {
    if (process.arch === "arm64") {
      try {
        return require("./xberg-node.openharmony-arm64.node");
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require("@xberg-io/xberg-openharmony-arm64");
        const bindingPackageVersion = require("@xberg-io/xberg-openharmony-arm64/package.json").version;
        if (
          bindingPackageVersion !== "1.3.7" &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === "x64") {
      try {
        return require("./xberg-node.openharmony-x64.node");
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require("@xberg-io/xberg-openharmony-x64");
        const bindingPackageVersion = require("@xberg-io/xberg-openharmony-x64/package.json").version;
        if (
          bindingPackageVersion !== "1.3.7" &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === "arm") {
      try {
        return require("./xberg-node.openharmony-arm.node");
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require("@xberg-io/xberg-openharmony-arm");
        const bindingPackageVersion = require("@xberg-io/xberg-openharmony-arm/package.json").version;
        if (
          bindingPackageVersion !== "1.3.7" &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0"
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`));
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`));
  }
}

function createLoadErrorChain(errors) {
  return errors.reduce((previous, current) => {
    let message;
    try {
      message = current && typeof current.message === "string" ? current.message : String(current);
    } catch {
      message = "Unknown error";
    }
    const error = new Error(message);
    error.cause = previous;
    return error;
  }, null);
}

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → prefer WASI, but retain native as a lazy fallback
//   'error'                  → require WASI without initializing a native fallback
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
//
// NAPI_RS_WASI_FLAVOR selects one exact generated flavor and implies strict
// WASI loading. It never crosses into another flavor or falls back to native.
const __napiWasiFlavors = ["wasm32-wasi"];
const __napiWasiFlavor = process.env.NAPI_RS_WASI_FLAVOR;
const __napiWasiFlavorRequested = typeof __napiWasiFlavor === "string" && __napiWasiFlavor.length > 0;
if (__napiWasiFlavorRequested && __napiWasiFlavors.indexOf(__napiWasiFlavor) === -1) {
  throw new Error(
    'Unsupported WASI flavor "' + __napiWasiFlavor + '". Available flavors: ' + __napiWasiFlavors.join(", "),
  );
}
const forceWasiError = process.env.NAPI_RS_FORCE_WASI === "error";
const forceWasi = process.env.NAPI_RS_FORCE_WASI === "true" || forceWasiError || __napiWasiFlavorRequested;

if (!forceWasi) {
  nativeBinding = requireNative();
}

if (!nativeBinding || forceWasi) {
  let wasiBinding = null;
  let wasiBindingLoaded = false;
  const wasiBindingErrors = [];
  const __napiWasiResolveCandidate = (specifier, isPackage, localArtifacts) => {
    try {
      require.resolve(specifier);
    } catch (resolveError) {
      if (!resolveError || resolveError.code !== "MODULE_NOT_FOUND") {
        throw resolveError;
      }
      if (isPackage) {
        try {
          require.resolve(specifier + "/package.json");
        } catch (packageError) {
          if (packageError && packageError.code === "MODULE_NOT_FOUND") {
            return resolveError;
          }
          // An exports restriction proves the package exists even when its
          // package.json is not public. Preserve the root resolution failure.
          throw resolveError;
        }
        // The package exists but its main/export target is broken.
        throw resolveError;
      }
      return resolveError;
    }
    if (localArtifacts) {
      let artifactError = null;
      for (let i = 0; i < localArtifacts.length; i++) {
        try {
          require.resolve(localArtifacts[i]);
          return null;
        } catch (resolveError) {
          if (!resolveError || resolveError.code !== "MODULE_NOT_FOUND") {
            throw resolveError;
          }
          artifactError = resolveError;
        }
      }
      return artifactError;
    }
    return null;
  };
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === "wasm32-wasi")) {
    let candidateError = null;
    let candidateFailed = false;
    try {
      candidateError = __napiWasiResolveCandidate("./xberg-node.wasi.cjs", false, [
        "./xberg-node.wasm32-wasi.debug.wasm",
        "./xberg-node.wasm32-wasi.wasm",
      ]);
      candidateFailed = candidateError !== null;
      if (!candidateFailed) {
        wasiBinding = require("./xberg-node.wasi.cjs");
        nativeBinding = wasiBinding;
        __napiLoadedBindingTarget = "wasm32-wasi";
        wasiBindingLoaded = true;
      }
    } catch (err) {
      candidateError = err;
      candidateFailed = true;
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError);
      loadErrors.push(candidateError);
    }
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === "wasm32-wasi")) {
    let candidateError = null;
    let candidateFailed = false;
    try {
      candidateError = __napiWasiResolveCandidate("@xberg-io/xberg-wasm32-wasi", true, undefined);
      candidateFailed = candidateError !== null;
      if (!candidateFailed) {
        if (process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== "0") {
          const bindingPackageVersion = require("@xberg-io/xberg-wasm32-wasi/package.json").version;
          if (bindingPackageVersion !== "1.3.7") {
            throw new Error(
              `WASI binding package version mismatch, expected 1.3.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
        }
        wasiBinding = require("@xberg-io/xberg-wasm32-wasi");
        nativeBinding = wasiBinding;
        __napiLoadedBindingTarget = "wasm32-wasi";
        wasiBindingLoaded = true;
      }
    } catch (err) {
      candidateError = err;
      candidateFailed = true;
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError);
      loadErrors.push(candidateError);
    }
  }
  if (!wasiBindingLoaded && forceWasi && !forceWasiError && !__napiWasiFlavorRequested) {
    nativeBinding = requireNative();
  }
  if ((forceWasiError || __napiWasiFlavorRequested) && !wasiBindingLoaded) {
    const error = new Error(
      __napiWasiFlavorRequested
        ? 'WASI binding for flavor "' + __napiWasiFlavor + '" not found'
        : "WASI binding not found and NAPI_RS_FORCE_WASI is set to error",
    );
    error.cause = createLoadErrorChain(wasiBindingErrors);
    throw error;
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        "Please try `npm i` again after removing both package-lock.json and node_modules directory.",
    );
    // assign instead of the `new Error(message, { cause })` options form,
    // which Node < 16.9 silently ignores
    error.cause = createLoadErrorChain(loadErrors);
    throw error;
  }
  throw new Error(`Failed to load native binding`);
}

function __napiStampBindingTarget(exportsObject, target) {
  if (Object.prototype.hasOwnProperty.call(exportsObject, "__napiBindingTarget")) {
    if (exportsObject.__napiBindingTarget === target) {
      // Already ours: the root entry aliases the object it loaded, so a WASI
      // fallback candidate — or a `NAPI_RS_NATIVE_LIBRARY_PATH` override that
      // is a generated loader — arrives already stamped with this same value.
      return target;
    }
    const error = new Error(
      '`__napiBindingTarget` is reserved by the generated binding loader, but the loaded binding already exports it. Rename the export, e.g. #[napi(js_name = "...")].',
    );
    error.code = "ERR_NAPI_BINDING_TARGET_CONFLICT";
    throw error;
  }
  if (!Object.isExtensible(exportsObject)) {
    // A `#[napi(module_exports)]` hook may seal or freeze this object
    // (`Object::seal` / `Object::freeze`). Reporting the artifact is metadata,
    // never a reason to fail an otherwise successful load, so the stamp is
    // skipped. What a consumer still sees then follows the entry point: the
    // browser and deferred loaders declare `__napiBindingTarget` at module
    // level and go on reporting it, while the CommonJS entries hand back this
    // very object as `module.exports`, so there the value is absent.
    return target;
  }
  try {
    // [[Define]], not [[Set]]: an ordinary assignment walks the prototype
    // chain, so an inherited accessor could swallow the value or throw and
    // fail an otherwise successful load. The descriptor is what a successful
    // assignment would have produced.
    Object.defineProperty(exportsObject, "__napiBindingTarget", {
      configurable: true,
      enumerable: true,
      value: target,
      writable: true,
    });
  } catch {
    // Same rule as the non-extensible skip above: reporting the artifact is
    // metadata, never a reason to fail an otherwise successful load. An exotic
    // object (a Proxy whose defineProperty trap refuses) is skipped, not
    // thrown over.
  }
  // The CommonJS loaders assign this return value so `cjs-module-lexer` — and
  // therefore Node's CJS -> ESM named export detection — can see
  // `__napiBindingTarget` statically.
  return target;
}
// Stamp before the alias, not after. The guard only reads `nativeBinding`
// (`hasOwnProperty` plus a comparison), which is safe against any addon
// accessor; an assignment is not, because a `#[napi(module_exports)]` hook can
// expose a getter reporting this very value and a setter that throws. So the
// assignment lands on the loader's own `module.exports`, still the original
// object here, and the alias below replaces it.
//
// The assignment is what keeps the marker a statically visible CommonJS export:
// `cjs-module-lexer` is Node's CJS -> ESM named export detection, it cannot see
// a bare call, and the later `module.exports = nativeBinding` does not undo the
// detection. The assignment itself always succeeds — its target is this
// loader's own, still extensible `module.exports` — and the alias below then
// discards the value it wrote. What a consumer reads is whatever the guard put
// on `nativeBinding`, so on a frozen binding, where the guard skips, the
// linked import resolves to `undefined`.
module.exports.__napiBindingTarget = __napiStampBindingTarget(nativeBinding, __napiLoadedBindingTarget);
module.exports = nativeBinding;
module.exports.DiffLine = nativeBinding.DiffLine;
module.exports.MetaSchema = nativeBinding.MetaSchema;
module.exports.JsMetaSchema = nativeBinding.JsMetaSchema;
module.exports.Registry = nativeBinding.Registry;
module.exports.JsRegistry = nativeBinding.JsRegistry;
module.exports.TokenCounter = nativeBinding.TokenCounter;
module.exports.JsTokenCounter = nativeBinding.JsTokenCounter;
module.exports.AssetCategory = nativeBinding.AssetCategory;
module.exports.JsAssetCategory = nativeBinding.JsAssetCategory;
module.exports.BlockType = nativeBinding.BlockType;
module.exports.JsBlockType = nativeBinding.JsBlockType;
module.exports.BoundaryReason = nativeBinding.BoundaryReason;
module.exports.JsBoundaryReason = nativeBinding.JsBoundaryReason;
module.exports.BrowserBackend = nativeBinding.BrowserBackend;
module.exports.JsBrowserBackend = nativeBinding.JsBrowserBackend;
module.exports.BrowserMode = nativeBinding.BrowserMode;
module.exports.JsBrowserMode = nativeBinding.JsBrowserMode;
module.exports.BrowserWait = nativeBinding.BrowserWait;
module.exports.JsBrowserWait = nativeBinding.JsBrowserWait;
module.exports.CallMode = nativeBinding.CallMode;
module.exports.JsCallMode = nativeBinding.JsCallMode;
module.exports.CandleDeepseekOcrDtype = nativeBinding.CandleDeepseekOcrDtype;
module.exports.JsCandleDeepseekOcrDtype = nativeBinding.JsCandleDeepseekOcrDtype;
module.exports.CandleDevicePreference = nativeBinding.CandleDevicePreference;
module.exports.JsCandleDevicePreference = nativeBinding.JsCandleDevicePreference;
module.exports.CandleTrocrVariant = nativeBinding.CandleTrocrVariant;
module.exports.JsCandleTrocrVariant = nativeBinding.JsCandleTrocrVariant;
module.exports.CaptionAltTextMode = nativeBinding.CaptionAltTextMode;
module.exports.JsCaptionAltTextMode = nativeBinding.JsCaptionAltTextMode;
module.exports.ChunkerType = nativeBinding.ChunkerType;
module.exports.JsChunkerType = nativeBinding.JsChunkerType;
module.exports.chunkingConfigDefault = nativeBinding.chunkingConfigDefault;
module.exports.ChunkType = nativeBinding.ChunkType;
module.exports.JsChunkType = nativeBinding.JsChunkType;
module.exports.classifyChunksOwned = nativeBinding.classifyChunksOwned;
module.exports.clearDocumentExtractors = nativeBinding.clearDocumentExtractors;
module.exports.clearEmbeddingBackends = nativeBinding.clearEmbeddingBackends;
module.exports.clearOcrBackends = nativeBinding.clearOcrBackends;
module.exports.clearPostProcessors = nativeBinding.clearPostProcessors;
module.exports.clearRenderers = nativeBinding.clearRenderers;
module.exports.clearRerankerBackends = nativeBinding.clearRerankerBackends;
module.exports.clearTokenizerBackends = nativeBinding.clearTokenizerBackends;
module.exports.clearValidators = nativeBinding.clearValidators;
module.exports.CodeBlockStyle = nativeBinding.CodeBlockStyle;
module.exports.JsCodeBlockStyle = nativeBinding.JsCodeBlockStyle;
module.exports.CodeContentMode = nativeBinding.CodeContentMode;
module.exports.JsCodeContentMode = nativeBinding.JsCodeContentMode;
module.exports.CodeDataNodeKind = nativeBinding.CodeDataNodeKind;
module.exports.JsCodeDataNodeKind = nativeBinding.JsCodeDataNodeKind;
module.exports.contentFilterConfigDefault = nativeBinding.contentFilterConfigDefault;
module.exports.ContentFilterKind = nativeBinding.ContentFilterKind;
module.exports.JsContentFilterKind = nativeBinding.JsContentFilterKind;
module.exports.ContentLayer = nativeBinding.ContentLayer;
module.exports.JsContentLayer = nativeBinding.JsContentLayer;
module.exports.CrawlStrategyKind = nativeBinding.CrawlStrategyKind;
module.exports.JsCrawlStrategyKind = nativeBinding.JsCrawlStrategyKind;
module.exports.diffOptionsDefault = nativeBinding.diffOptionsDefault;
module.exports.doctor = nativeBinding.doctor;
module.exports.doctorCheckFail = nativeBinding.doctorCheckFail;
module.exports.doctorCheckPass = nativeBinding.doctorCheckPass;
module.exports.doctorCheckSkip = nativeBinding.doctorCheckSkip;
module.exports.doctorCheckWarn = nativeBinding.doctorCheckWarn;
module.exports.DocumentContentEncoding = nativeBinding.DocumentContentEncoding;
module.exports.JsDocumentContentEncoding = nativeBinding.JsDocumentContentEncoding;
module.exports.documentStructureDefault = nativeBinding.documentStructureDefault;
module.exports.ElementType = nativeBinding.ElementType;
module.exports.JsElementType = nativeBinding.JsElementType;
module.exports.embeddingConfigDefault = nativeBinding.embeddingConfigDefault;
module.exports.EmbeddingsEmbeddingBackend = nativeBinding.EmbeddingsEmbeddingBackend;
module.exports.JsEmbeddingsEmbeddingBackend = nativeBinding.JsEmbeddingsEmbeddingBackend;
module.exports.ExecutionProviderType = nativeBinding.ExecutionProviderType;
module.exports.JsExecutionProviderType = nativeBinding.JsExecutionProviderType;
module.exports.extract = nativeBinding.extract;
module.exports.extractBatch = nativeBinding.extractBatch;
module.exports.extractInputDefault = nativeBinding.extractInputDefault;
module.exports.extractInputFromBytes = nativeBinding.extractInputFromBytes;
module.exports.extractInputFromUri = nativeBinding.extractInputFromUri;
module.exports.ExtractInputKind = nativeBinding.ExtractInputKind;
module.exports.JsExtractInputKind = nativeBinding.JsExtractInputKind;
module.exports.extractionConfigDefault = nativeBinding.extractionConfigDefault;
module.exports.ExtractionMethod = nativeBinding.ExtractionMethod;
module.exports.JsExtractionMethod = nativeBinding.JsExtractionMethod;
module.exports.extractionResultSingle = nativeBinding.extractionResultSingle;
module.exports.extractWithExternalRedaction = nativeBinding.extractWithExternalRedaction;
module.exports.findUnmarkedClaims = nativeBinding.findUnmarkedClaims;
module.exports.footnoteConfigDefault = nativeBinding.footnoteConfigDefault;
module.exports.footnoteConfigWithParseCitations = nativeBinding.footnoteConfigWithParseCitations;
module.exports.FormFieldType = nativeBinding.FormFieldType;
module.exports.JsFormFieldType = nativeBinding.JsFormFieldType;
module.exports.FormulaModel = nativeBinding.FormulaModel;
module.exports.JsFormulaModel = nativeBinding.JsFormulaModel;
module.exports.GlmOcrLayoutMode = nativeBinding.GlmOcrLayoutMode;
module.exports.JsGlmOcrLayoutMode = nativeBinding.JsGlmOcrLayoutMode;
module.exports.GlmOcrTaskKind = nativeBinding.GlmOcrTaskKind;
module.exports.JsGlmOcrTaskKind = nativeBinding.JsGlmOcrTaskKind;
module.exports.HeadingStyle = nativeBinding.HeadingStyle;
module.exports.JsHeadingStyle = nativeBinding.JsHeadingStyle;
module.exports.heuristicsConfigDefault = nativeBinding.heuristicsConfigDefault;
module.exports.hierarchyConfigDefault = nativeBinding.hierarchyConfigDefault;
module.exports.HighlightStyle = nativeBinding.HighlightStyle;
module.exports.JsHighlightStyle = nativeBinding.JsHighlightStyle;
module.exports.htmlOutputConfigDefault = nativeBinding.htmlOutputConfigDefault;
module.exports.HtmlTheme = nativeBinding.HtmlTheme;
module.exports.JsHtmlTheme = nativeBinding.JsHtmlTheme;
module.exports.HtmlToMarkdownRsOutputFormat = nativeBinding.HtmlToMarkdownRsOutputFormat;
module.exports.JsHtmlToMarkdownRsOutputFormat = nativeBinding.JsHtmlToMarkdownRsOutputFormat;
module.exports.imageExtractionConfigDefault = nativeBinding.imageExtractionConfigDefault;
module.exports.ImageKind = nativeBinding.ImageKind;
module.exports.JsImageKind = nativeBinding.JsImageKind;
module.exports.imagePreprocessingConfigDefault = nativeBinding.imagePreprocessingConfigDefault;
module.exports.ImageType = nativeBinding.ImageType;
module.exports.JsImageType = nativeBinding.JsImageType;
module.exports.InlineDataMedia = nativeBinding.InlineDataMedia;
module.exports.JsInlineDataMedia = nativeBinding.JsInlineDataMedia;
module.exports.InlineType = nativeBinding.InlineType;
module.exports.JsInlineType = nativeBinding.JsInlineType;
module.exports.JupyterCellRendering = nativeBinding.JupyterCellRendering;
module.exports.JsJupyterCellRendering = nativeBinding.JsJupyterCellRendering;
module.exports.KeywordAlgorithm = nativeBinding.KeywordAlgorithm;
module.exports.JsKeywordAlgorithm = nativeBinding.JsKeywordAlgorithm;
module.exports.keywordConfigDefault = nativeBinding.keywordConfigDefault;
module.exports.languageDetectionConfigDefault = nativeBinding.languageDetectionConfigDefault;
module.exports.lateInteractionConfigDefault = nativeBinding.lateInteractionConfigDefault;
module.exports.LayoutClass = nativeBinding.LayoutClass;
module.exports.JsLayoutClass = nativeBinding.JsLayoutClass;
module.exports.layoutDetectionConfigDefault = nativeBinding.layoutDetectionConfigDefault;
module.exports.LayoutStrategy = nativeBinding.LayoutStrategy;
module.exports.JsLayoutStrategy = nativeBinding.JsLayoutStrategy;
module.exports.LinkStyle = nativeBinding.LinkStyle;
module.exports.JsLinkStyle = nativeBinding.JsLinkStyle;
module.exports.LinkType = nativeBinding.LinkType;
module.exports.JsLinkType = nativeBinding.JsLinkType;
module.exports.listDocumentExtractors = nativeBinding.listDocumentExtractors;
module.exports.listEmbeddingBackends = nativeBinding.listEmbeddingBackends;
module.exports.ListIndentType = nativeBinding.ListIndentType;
module.exports.JsListIndentType = nativeBinding.JsListIndentType;
module.exports.listOcrBackendCapabilities = nativeBinding.listOcrBackendCapabilities;
module.exports.listOcrBackendCapabilitiesFor = nativeBinding.listOcrBackendCapabilitiesFor;
module.exports.listOcrBackends = nativeBinding.listOcrBackends;
module.exports.listPostProcessors = nativeBinding.listPostProcessors;
module.exports.listRenderers = nativeBinding.listRenderers;
module.exports.listRerankerBackends = nativeBinding.listRerankerBackends;
module.exports.listSupportedFormats = nativeBinding.listSupportedFormats;
module.exports.listTokenizerBackends = nativeBinding.listTokenizerBackends;
module.exports.ListType = nativeBinding.ListType;
module.exports.JsListType = nativeBinding.JsListType;
module.exports.listValidators = nativeBinding.listValidators;
module.exports.mapUrl = nativeBinding.mapUrl;
module.exports.maxSimRank = nativeBinding.maxSimRank;
module.exports.maxSimScore = nativeBinding.maxSimScore;
module.exports.MergeMode = nativeBinding.MergeMode;
module.exports.JsMergeMode = nativeBinding.JsMergeMode;
module.exports.MimeDetectionPolicy = nativeBinding.MimeDetectionPolicy;
module.exports.JsMimeDetectionPolicy = nativeBinding.JsMimeDetectionPolicy;
module.exports.multidocThresholdsDefault = nativeBinding.multidocThresholdsDefault;
module.exports.NerBackendKind = nativeBinding.NerBackendKind;
module.exports.JsNerBackendKind = nativeBinding.JsNerBackendKind;
module.exports.NewlineStyle = nativeBinding.NewlineStyle;
module.exports.JsNewlineStyle = nativeBinding.JsNewlineStyle;
module.exports.ngramRangeDefault = nativeBinding.ngramRangeDefault;
module.exports.ocrBackendSupportsLanguage = nativeBinding.ocrBackendSupportsLanguage;
module.exports.ocrBackendSupportsLanguageFor = nativeBinding.ocrBackendSupportsLanguageFor;
module.exports.OcrBackendType = nativeBinding.OcrBackendType;
module.exports.JsOcrBackendType = nativeBinding.JsOcrBackendType;
module.exports.ocrConfigDefault = nativeBinding.ocrConfigDefault;
module.exports.OcrElementLevel = nativeBinding.OcrElementLevel;
module.exports.JsOcrElementLevel = nativeBinding.JsOcrElementLevel;
module.exports.ocrQualityThresholdsDefault = nativeBinding.ocrQualityThresholdsDefault;
module.exports.PaddleInferenceBackend = nativeBinding.PaddleInferenceBackend;
module.exports.JsPaddleInferenceBackend = nativeBinding.JsPaddleInferenceBackend;
module.exports.PaddleLanguage = nativeBinding.PaddleLanguage;
module.exports.JsPaddleLanguage = nativeBinding.JsPaddleLanguage;
module.exports.paddleOcrConfigDefault = nativeBinding.paddleOcrConfigDefault;
module.exports.paddleOcrConfigWithAngleCls = nativeBinding.paddleOcrConfigWithAngleCls;
module.exports.paddleOcrConfigWithCacheDir = nativeBinding.paddleOcrConfigWithCacheDir;
module.exports.paddleOcrConfigWithDetDbBoxThresh = nativeBinding.paddleOcrConfigWithDetDbBoxThresh;
module.exports.paddleOcrConfigWithDetDbThresh = nativeBinding.paddleOcrConfigWithDetDbThresh;
module.exports.paddleOcrConfigWithDetDbUnclipRatio = nativeBinding.paddleOcrConfigWithDetDbUnclipRatio;
module.exports.paddleOcrConfigWithDetLimitSideLen = nativeBinding.paddleOcrConfigWithDetLimitSideLen;
module.exports.paddleOcrConfigWithDropScore = nativeBinding.paddleOcrConfigWithDropScore;
module.exports.paddleOcrConfigWithModelTier = nativeBinding.paddleOcrConfigWithModelTier;
module.exports.paddleOcrConfigWithModelVersion = nativeBinding.paddleOcrConfigWithModelVersion;
module.exports.paddleOcrConfigWithPadding = nativeBinding.paddleOcrConfigWithPadding;
module.exports.paddleOcrConfigWithRecBatchNum = nativeBinding.paddleOcrConfigWithRecBatchNum;
module.exports.paddleOcrConfigWithTableDetection = nativeBinding.paddleOcrConfigWithTableDetection;
module.exports.PaddleOcrVlTaskKind = nativeBinding.PaddleOcrVlTaskKind;
module.exports.JsPaddleOcrVlTaskKind = nativeBinding.JsPaddleOcrVlTaskKind;
module.exports.pageConfigDefault = nativeBinding.pageConfigDefault;
module.exports.PageOrientationHandling = nativeBinding.PageOrientationHandling;
module.exports.JsPageOrientationHandling = nativeBinding.JsPageOrientationHandling;
module.exports.pageSignalsFromPageText = nativeBinding.pageSignalsFromPageText;
module.exports.PageUnitType = nativeBinding.PageUnitType;
module.exports.JsPageUnitType = nativeBinding.JsPageUnitType;
module.exports.PdfAnnotationType = nativeBinding.PdfAnnotationType;
module.exports.JsPdfAnnotationType = nativeBinding.JsPdfAnnotationType;
module.exports.PdfBackend = nativeBinding.PdfBackend;
module.exports.JsPdfBackend = nativeBinding.JsPdfBackend;
module.exports.pdfConfigDefault = nativeBinding.pdfConfigDefault;
module.exports.pdfPageCount = nativeBinding.pdfPageCount;
module.exports.postProcessorConfigDefault = nativeBinding.postProcessorConfigDefault;
module.exports.PreprocessingPreset = nativeBinding.PreprocessingPreset;
module.exports.JsPreprocessingPreset = nativeBinding.JsPreprocessingPreset;
module.exports.PresetCategory = nativeBinding.PresetCategory;
module.exports.JsPresetCategory = nativeBinding.JsPresetCategory;
module.exports.ProbeStatus = nativeBinding.ProbeStatus;
module.exports.JsProbeStatus = nativeBinding.JsProbeStatus;
module.exports.ProcessingStage = nativeBinding.ProcessingStage;
module.exports.JsProcessingStage = nativeBinding.JsProcessingStage;
module.exports.PSMMode = nativeBinding.PSMMode;
module.exports.JsPSMMode = nativeBinding.JsPSMMode;
module.exports.rakeParamsDefault = nativeBinding.rakeParamsDefault;
module.exports.redactExternal = nativeBinding.redactExternal;
module.exports.redactionConfigDefault = nativeBinding.redactionConfigDefault;
module.exports.RedactionOffsetEncoding = nativeBinding.RedactionOffsetEncoding;
module.exports.JsRedactionOffsetEncoding = nativeBinding.JsRedactionOffsetEncoding;
module.exports.redactionPatternLabeled = nativeBinding.redactionPatternLabeled;
module.exports.RedactionStrategy = nativeBinding.RedactionStrategy;
module.exports.JsRedactionStrategy = nativeBinding.JsRedactionStrategy;
module.exports.redactionTermLabeled = nativeBinding.redactionTermLabeled;
module.exports.redactionTermLiteral = nativeBinding.redactionTermLiteral;
module.exports.ReductionLevel = nativeBinding.ReductionLevel;
module.exports.JsReductionLevel = nativeBinding.JsReductionLevel;
module.exports.RegionKind = nativeBinding.RegionKind;
module.exports.JsRegionKind = nativeBinding.JsRegionKind;
module.exports.registerDocumentExtractor = nativeBinding.registerDocumentExtractor;
module.exports.registerEmbeddingBackend = nativeBinding.registerEmbeddingBackend;
module.exports.registerOcrBackend = nativeBinding.registerOcrBackend;
module.exports.registerPostProcessor = nativeBinding.registerPostProcessor;
module.exports.registerRenderer = nativeBinding.registerRenderer;
module.exports.registerRerankerBackend = nativeBinding.registerRerankerBackend;
module.exports.registerTokenizerBackend = nativeBinding.registerTokenizerBackend;
module.exports.registerValidator = nativeBinding.registerValidator;
module.exports.RelationshipKind = nativeBinding.RelationshipKind;
module.exports.JsRelationshipKind = nativeBinding.JsRelationshipKind;
module.exports.rerankerConfigDefault = nativeBinding.rerankerConfigDefault;
module.exports.RerankerHead = nativeBinding.RerankerHead;
module.exports.JsRerankerHead = nativeBinding.JsRerankerHead;
module.exports.ResultFormat = nativeBinding.ResultFormat;
module.exports.JsResultFormat = nativeBinding.JsResultFormat;
module.exports.RevisionKind = nativeBinding.RevisionKind;
module.exports.JsRevisionKind = nativeBinding.JsRevisionKind;
module.exports.SchemaCompliance = nativeBinding.SchemaCompliance;
module.exports.JsSchemaCompliance = nativeBinding.JsSchemaCompliance;
module.exports.securityLimitsDefault = nativeBinding.securityLimitsDefault;
module.exports.serverConfigDefault = nativeBinding.serverConfigDefault;
module.exports.sparseEmbeddingConfigDefault = nativeBinding.sparseEmbeddingConfigDefault;
module.exports.StructuredDataType = nativeBinding.StructuredDataType;
module.exports.JsStructuredDataType = nativeBinding.JsStructuredDataType;
module.exports.SummaryStrategy = nativeBinding.SummaryStrategy;
module.exports.JsSummaryStrategy = nativeBinding.JsSummaryStrategy;
module.exports.svgOptionsDefault = nativeBinding.svgOptionsDefault;
module.exports.TableChunkingMode = nativeBinding.TableChunkingMode;
module.exports.JsTableChunkingMode = nativeBinding.JsTableChunkingMode;
module.exports.TableModel = nativeBinding.TableModel;
module.exports.JsTableModel = nativeBinding.JsTableModel;
module.exports.TableOverlapPreference = nativeBinding.TableOverlapPreference;
module.exports.JsTableOverlapPreference = nativeBinding.JsTableOverlapPreference;
module.exports.tesseractConfigDefault = nativeBinding.tesseractConfigDefault;
module.exports.TextDirection = nativeBinding.TextDirection;
module.exports.JsTextDirection = nativeBinding.JsTextDirection;
module.exports.TierStrategy = nativeBinding.TierStrategy;
module.exports.JsTierStrategy = nativeBinding.JsTierStrategy;
module.exports.tokenReductionConfigDefault = nativeBinding.tokenReductionConfigDefault;
module.exports.tokenReductionOptionsDefault = nativeBinding.tokenReductionOptionsDefault;
module.exports.transcriptionConfigDefault = nativeBinding.transcriptionConfigDefault;
module.exports.treeSitterConfigDefault = nativeBinding.treeSitterConfigDefault;
module.exports.treeSitterProcessConfigDefault = nativeBinding.treeSitterProcessConfigDefault;
module.exports.unregisterDocumentExtractor = nativeBinding.unregisterDocumentExtractor;
module.exports.unregisterEmbeddingBackend = nativeBinding.unregisterEmbeddingBackend;
module.exports.unregisterOcrBackend = nativeBinding.unregisterOcrBackend;
module.exports.unregisterPostProcessor = nativeBinding.unregisterPostProcessor;
module.exports.unregisterRenderer = nativeBinding.unregisterRenderer;
module.exports.unregisterRerankerBackend = nativeBinding.unregisterRerankerBackend;
module.exports.unregisterTokenizerBackend = nativeBinding.unregisterTokenizerBackend;
module.exports.unregisterValidator = nativeBinding.unregisterValidator;
module.exports.UriKind = nativeBinding.UriKind;
module.exports.JsUriKind = nativeBinding.JsUriKind;
module.exports.UrlEscapeStyle = nativeBinding.UrlEscapeStyle;
module.exports.JsUrlEscapeStyle = nativeBinding.JsUrlEscapeStyle;
module.exports.urlExtractionConfigDefault = nativeBinding.urlExtractionConfigDefault;
module.exports.UrlExtractionMode = nativeBinding.UrlExtractionMode;
module.exports.JsUrlExtractionMode = nativeBinding.JsUrlExtractionMode;
module.exports.verifyExcerpt = nativeBinding.verifyExcerpt;
module.exports.WhisperModel = nativeBinding.WhisperModel;
module.exports.JsWhisperModel = nativeBinding.JsWhisperModel;
module.exports.WhitespaceMode = nativeBinding.WhitespaceMode;
module.exports.JsWhitespaceMode = nativeBinding.JsWhitespaceMode;
module.exports.yakeParamsDefault = nativeBinding.yakeParamsDefault;
