# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0687e037476da4ba7e18fe1957eb56d2d154c61c20f178f4c8ee9e1cc7d090c2
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.3.7"
end
